<?xml version="1.0" encoding="utf-8"?><Database Name="BdayBuddy" Class="BdayBuddyLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\BdayBuddy.mdf;Integrated Security=True" SettingsObjectName="BdayBuddy.Properties.Settings" SettingsPropertyName="BdayBuddyConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ctable" Member="ctables">
    <Type Name="ctable">
      <Column Name="IndexNumber" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dateOfBirth" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SignTable" Member="SignTables">
    <Type Name="SignTable">
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>